# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: wapt_db
    ports:
      - 27017:27017
  server:
    build: ./server/
    env_file:
      - ./server/.env
    ports:
      - 8000:8000
    links:
      - "mongo"
  toolkit:
    build: ./toolkit/
    ports:
      - 5000:5000
  client:
    build: ./client/
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    links:
      - server:server.local
      - toolkit
